### ISSUE TITLE
Support for Android 4.4 bug

### ISSUE THREAD

**Issue by mitroo** [dudeonthehorse/normalize.email.css#1]
There is a bug on Android 4.4 that makes the whole email moved to the right, hiding it's content.
The bug is described in detail [here](https://litmus.com/community/discussions/4194-why-is-email-not-centered-on-android-4-4). It would be nice if you'll add support for this also 😊

**Comment by dudeonthehorse** [comment]
Sure I know about this bug. But nulled `margin` of `<body>` element is already not default styling. It conflicts with minimal emails.
