### ISSUE TITLE
What do you mean by inline

### ISSUE THREAD

**Issue by hvanoch** [dudeonthehorse/normalize.email.css#2]
You say "normalize.css - must be inlined to your newsletter in production"

What do you mean by inline? Inline on what html tag? Or do you also mean by putting it between <style> tags?

**Comment by maksim-shabanski** [comment]
You need to embed these styles into html tags.

Example:
`<p style="color:#000;font-size:16px;">Text</p>`

**Comment by dudeonthehorse** [comment]
Hello, @hvanoch. 

By inlining i mean using css-inliner tool. 

For example:
- https://inliner.cm/ for manual usage
- https://www.npmjs.com/package/inline-css as npm-package

The contents of `extra.css` and `outlook.css` must be placed in `head` of newsletter, but not required to be inlined
